name: "⚙ Check latest Lens version"

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  version_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the latest version of Lens
        run: |
          set -o pipefail
          curl -s https://api.github.com/repos/lensapp/lens/releases | jq -r '[.[] | select(.prerelease == false)][0] | .tag_name[1:]' > version
          echo "LENS_VERSION=$(cat version)" >> $GITHUB_ENV
          
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: 'Version updated to: ${{ env.LENS_VERSION }}'
