name: Clear Latest

on:
  workflow_dispatch:
          
jobs:
  build:
    runs-on: ubuntu
    timeout-minutes: 5
    steps:
      - name: Clean Latest
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: Latest
          fail-if-no-assets: false
          fail-if-no-release: false
          assets: | 
            *.*
